name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  ECP_REPO_URL: https://github.com/VFrontDe/ESXi-Customizer-PS
  ECP_REPO_BRANCH: master

jobs:
  build:
    name: "TEST"
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Test1
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          git clone ${{ env.ECP_REPO_URL }} -b ${{ env.ECP_REPO_BRANCH }} ECP
          ls
          $PSfile = "& ${{ github.workspace }}\test.ps1"
          echo $PSfile
          iex $PSfile
          cd ECP
          ls